package sk.tsystems.forum.entity.common;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import javax.persistence.OneToOne;

import sk.tsystems.forum.entity.Blocked;

@MappedSuperclass
public class BlockableEntity {
	
	/**
	 * ID. Generated by hibernate
	 */
	@Id
	@GeneratedValue
	private int id;
	
	/**
	 * One-To-One connection between user and blocked
	 */
	@OneToOne
	private Blocked blocked;

	/**
	 * Getter for ID
	 * 
	 * @return ID
	 */	
	public int getId() {
		return id;
	}
	
	/**
	 * Getter for blocked
	 * 
	 * @return blocked
	 */
	public Blocked getBlocked() {
		return blocked;
	}

	/**
	 * Setter for blocked
	 * 
	 * @param blocked
	 */
	public void setBlocked(Blocked blocked) {
		this.blocked = blocked;
	}
}