package sk.tsystems.forum.entity.common;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 * Common entity properties class
 * This is superclass for all entities
 * Implements common properties, "shared" by all entities  
 * @author Dalibor
 */
@MappedSuperclass
public abstract class CommonEntity {
	
	/**
	 * Entity ID. 
	 * Generated by hibernate
	 */
	@Id
	@GeneratedValue
	@Column(name = "ID")
	private final int id;
	
	/**
	 * Creation date
	 * Date and time of entity create
	 */
	@Column(name = "CREATEDATE", nullable = false)
	private final Date created;

	/**
	 * Default constructor for Common Entity
	 * This constructor assigns creation time + date to current time + date
	 */
	protected CommonEntity() {
		super();
		this.id =0;
		this.created = new Date();
	}

	/**
	 * Getter for ID
	 * Gets an unique ID of entity.
	 * <p>An <b>non - persisted entity<b> has assigned ID value of zero <i>(ID = 0)</i>.</p>
	 * <p>An <b>persisted entity<b> has assigned ID value higher than zero <i>(ID > 0)</i>.</p>
	 * <p>Value is assigned to entity at fist persist. It wouldn'd be changed.</p>
	 * <b>This method cannot be overriden</b>
	 * @return an unique ID for persisted entity ( ID > 0) otherwise zero value (0) 
	 */	
	public final int getId() {
		return id;
	}

	/**
	 * Getter for Date of entity creation
	 * <p>An <b>non - persisted entity<b> has assigned current date and time on creation.</i></p>
	 * <p>An <b>persisted entity<b> has assigned an stored date and time of first creation.</i></p>
	 * <p>Value is assigned to entity at fist create. It wouldn'd be changed.</p>
	 * @return Date and time assigned to entity on creation
	 */
	public final Date getCreated() {
		return created;
	}
}