package sk.tsystems.forum.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;

@Entity
public class Blocked {

	/**
	 * ID. Generated automatically by Hibernate
	 */
	@Id
	@GeneratedValue
	private int id;
	/**
	 * User(admin) that created the block
	 */
	@OneToOne
	private User blockedBy;

	/**
	 * Date of block. Generated by current date in constructor
	 */
	@Column(name = "BLOCKDATE", nullable = false)
	private Date blockdate;

	/**
	 * Reason of the block
	 */
	@Column(name = "REASON", nullable = false)
	private String reason;

	public Blocked(User blockedBy, String reason) {
		this();
		setBlockedBy(blockedBy);
		setReason(reason);
	}

	/**
	 * constructor for JPA
	 */
	private Blocked() {
		super();
		this.blockdate = new Date();
	}

	/**
	 * Getter for blockedBy
	 * 
	 * @return blockedBy
	 */
	public User getBlockedBy() {
		return blockedBy;
	}

	/**
	 * setter for blockedBy
	 * @param blockedBy
	 */
	public void setBlockedBy(User blockedBy) {
		this.blockedBy = blockedBy;
	}

	/**
	 * Getter for block date
	 * 
	 * @return blockdate
	 */
	public Date getBlockdate() {
		return blockdate;
	}

	/**
	 * Getter for reason
	 * 
	 * @return reason
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * Setter for reason
	 * @param reason
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

}
