package sk.tsystems.forum.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import sk.tsystems.forum.entity.common.BlockableEntity;

@Entity
@Table(name = "TOPIC")
public class Topic  extends BlockableEntity {
	/**
	 * ID. Generated automatically by Hibernate
	 */
//	@Id
//	@GeneratedValue
//	private int id;
	
	/**
	 * name of the topic
	 * 
	 */
	@Column(name = "NAME", nullable = false,unique=true)
	private String name;
	
	/**
	 * Public status for topic
	 */
	@Column(name = "ISPUBLIC", nullable = false)
	private boolean isPublic;
	// TODO implementovat list kommentov ak nam ho bude treba
	// @OneToMany
	// List<Comment> comments;
	
	/**
	 * Creation date. Generated by current date in constructor
	 */
	@Column(name = "CREATIONDATE", nullable = false)
	private Date creationDate;
	
	public Topic(String name, boolean isPublic) {
		super();
		this.name = name;
		this.isPublic = isPublic;
		this.creationDate = new Date();

	}

	@Deprecated
	public Topic() {
		this(null, false);
	}
	
	/**
	 * Getter for name
	 * @return name
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * Setter for name
	 * @param name
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	/**
	 * Getter for isPublic
	 * @return isPublic
	 */
	public boolean isIsPublic() {
		return isPublic;
	}

	/**
	 * Setter for isPublic
	 * @param isPublic
	 */
	public void setPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}
	
	/**
	 * Getter for creationDate
	 * @return creationDate
	 */
	public Date getCreationDate() {
		return creationDate;
	}
	
	/**
	 * Getter for ID
	 * @return ID
	 */
//	public int getId() {
//		return id;
//	}

}
